sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
before_script:
  - PATH=${PATH//:\.\/node_modules\/\.bin/}
after_success:
  - npm run build
  - npm run coverage
  - npm install -g travis-deploy-once
  - travis-deploy-once "npm run semantic-release"
branches:
  only:
    - master
    - dev
    - /^greenkeeper/.*$/
before_deploy:
  - cd examples
  - npm install
  - npm run build
# https://docs.travis-ci.com/user/deployment/script
deploy:
  provider: script
  script: pwd && npm run deploy
  on:
    branch: master
    node: '10'
